- name: change the directory
  shell: cd /home/ubuntu

- name: Download data-node package
  get_url:
    url:  https://dev.mysql.com/get/Downloads/MySQL-Cluster-8.0/mysql-cluster-community-data-node_8.0.30-1ubuntu20.04_amd64.deb
    dest: /home/ubuntu/mysql-cluster-community-data-node_8.0.30-1ubuntu20.04_amd64.deb

- name: install libclass-methodmaker-perl
  shell: apt install libclass-methodmaker-perl

- name: install data-node package
  shell: dpkg -i mysql-cluster-community-data-node_8.0.30-1ubuntu20.04_amd64.deb

- name: copy my.cnf file
  template:
    src: my.cnf
    dest: /etc/my.cnf

- name: Creates /usr/local/mysql/data directory
  file:
    path: /usr/local/mysql/data
    state: directory

- name: Install ndbd.service file
  copy: 
    src: ndbd.service
    dest: /etc/systemd/system/ndbd.service

- name: reload daemon
  shell: systemctl daemon-reload

- name: Initialize ndbd
  service:
    name: ndbd
    state: started
    enabled: yes