---
- name: Prepare Gitlab User
  hosts: gitlab_node
  become: true
  tasks:
    - name: install pytho3
      apt:
        name: python3
        state: latest

    - name: install python3-pip
      apt:
        name: python3-pip
        state: latest

    - name: install python-gitlab
      shell: python3 -m pip install python-gitlab




    - name: Set token for user root
      command: gitlab-rails runner "token = User.find_by_username('root').personal_access_tokens.create(scopes:[:api], name:'Automation token make by ansible'); token.set_token('"{{ gitlab_root_token }}"'); token.save!"
      ignore_errors: yes

##- name: Make Project
##  hosts: "127.0.0.1"
##  become: true
##  tasks:

    - name: Create GitLab Project
      community.general.gitlab_project:
        api_url: http://{{ gitlab_node_hostname }}
        api_token: "{{ gitlab_root_token }}"
        name: "{{ gitlab_project_name }}"

#    - name: "Create GitLab User"
#      community.general.gitlab_user:
#        api_url: https://gitlab.example.com/
#        validate_certs: true
#        api_username: dj-wasabi
#        api_password: "MySecretPassword"
#        name: My Name
#        username: myusername
#        password: mysecretpassword
#        email: me@example.com
#        sshkey_name: MySSH
#        sshkey_file: ssh-rsa AAAAB3NzaC1yc...
#        state: present
#        group: super_group/mon_group
#        access_level: owner



#    - name: Add ssh to root
#      community.general.gitlab_user:
#        api_url: https://{{ gitlab_node_hostname }}
#        validate_certs: true
#        api_token: "{{ gitlab_root_token }}"
##        api_username: root
##        api_password: "MySecretPassword"
#        name: root
#        username: root
#        password: "{{ gitlab_root_password }}"
#        email: me@example.com
#        sshkey_name: RootSSH
#        sshkey_file: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD2I0kNz0mxF86CFbmIAv8qG66cpgdcvDz7Slbpedb0jRnsns6IZGJCZnbYnDKwYHBvMGqsxoJAccFLlmNm2RJhzGdvPWT6T/S5YfDhu+4ZdnMYmtIZxCsYaBbOpmmr1mT/krz7KLbNWER7LTL9o14ixExH4k4CJAHIClbFbeZuRtIRG28VsfOGrUTPWvAj9x+++NXz9ZibJlxjyHvWN6G0yi7ZAoYHr2auk/KUUvUZ7qhWLH3d4zeTcqZV4r/mMe+4Nn0zapyq5pV8BH+gvTgF9QUij6KoTrf2MrxpfLWu1djfNYVD+BvtKUWsuzWDaliAr41ZM+yV4zog6vl2l3wf2eJpSByuUlpR6kf6c9jKWc4wgwKioReJoXm8raOnoRRjDjU0WgU0pADEPcO1pnhJelsJXbstwfCW07mIk1Tdu1Ug13+aWyukU9+7OIREIaGZUL1/L3OKy9ioHyqq+TfiiUiGhuRx0/uPDco8mEe9nQLMvDne+QrQPeDL5F6838kWRJxTErF/yy99GWO4SoXp7X5NuoUE8K4iDzpuMMM0pzAuUdejI5OOIgT+QyHpYA5m2oaLr+o86LQ/nY5omH2lpz8H8oJniZIv1hgU23+uBit/fkD0TkSZqKZAwnq/BYYJ4o4tHf01nlesJchvllhlioVy3hutzvp7Lxj9SBgvKQ== user1@work-vm-ubuntu
#        state: present
##        group: super_group/mon_group
#        access_level: owner
