
# Терраформ создаёт inventory файл для ansible для настройки gitlab_node и gitlabrunner_node
resource "local_file" "inventory_gitlab_nodes" {
  content = <<-DOC
# Ansible inventory containing variable values from Terraform.
# Generated by Terraform.
[nodes:children]
gitlab_nodes
gitlabrunner_nodes

[gitlab_nodes]
gitlab_node ansible_host=${aws_instance.diplom-vm-gitlab_node.private_ip} ansible_ssh_private_key_file=~/.ssh/${aws_key_pair.kp.key_name}.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q ubuntu@${aws_instance.diplom-vm-rproxy.public_ip} -i ~/.ssh/${aws_key_pair.kp.key_name}.pem -oStrictHostKeyChecking=accept-new"'

[gitlabrunner_nodes]
gitlabrunner_node ansible_host=${aws_instance.diplom-vm-gitlabrunner_node.private_ip} ansible_ssh_private_key_file=~/.ssh/${aws_key_pair.kp.key_name}.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q ubuntu@${aws_instance.diplom-vm-rproxy.public_ip} -i ~/.ssh/${aws_key_pair.kp.key_name}.pem -oStrictHostKeyChecking=accept-new"'

    DOC
  filename = "../ansible/gitlab_nodes/inventory_gitlab_nodes"

  depends_on = [
    aws_instance.diplom-vm-gitlab_node, aws_instance.diplom-vm-gitlabrunner_node,
  ]
}
