
# Терраформ создаёт inventory файл для ansible для настройки rproxy
resource "local_file" "inventory_rproxy" {
  content = <<-DOC
# Ansible inventory containing variable values from Terraform.
# Generated by Terraform.
[nodes:children]
rproxys
[rproxys]
rproxy ansible_host=${aws_instance.diplom-vm-rproxy.public_ip} ansible_ssh_private_key_file=~/.ssh/${aws_key_pair.kp.key_name}.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
    DOC
  filename = "../ansible/rproxy/inventory_rproxy"

  depends_on = [
    aws_instance.diplom-vm-rproxy
  ]
}
