---
  - name: "Change DNS zone of domain. Set public-ip rproxy to A-record"
    hosts: localhost
    connection: local
    tasks:

      - name: Delete old A-record with old IP
        community.general.cloudflare_dns:
          zone: "{{ domain_name }}"
          record: "@"
          type: A
          api_token: t44iHmKOjkxjsRvyyLzw27jCQb1WMT2DSr6IUgkI
          state: absent

      - name: Create A-record with new IP
        community.general.cloudflare_dns:
          zone: "{{ domain_name }}"
          record: "@"
          type: A
          value: "{{ rproxy_public_ip }}"
          ttl: 60
          api_token: t44iHmKOjkxjsRvyyLzw27jCQb1WMT2DSr6IUgkI
          state: present