- name: install apache & php
  hosts: all
  become: true
  gather_facts: true
  tasks:

    - name: Install apache and php neededs
      apt:
        package:
            - apache2
            - libapache2-mod-php
            - php-cli
            - php-gd
            - php-fpm
            - php-common
            - php-mbstring
            - php-xmlrpc
            - php-xml
            - php-mysql
            - php-zip
            - php-curl
        state: present
        force: yes
        update_cache: yes

