---

# Выполняем Действия актуальные для всех серверов
# В том числе установка node-exporter
- hosts: all
  become: true
  roles:
    - common

# Переименовываем все серверы. То есть меняем внутри них hostname
# Пришлось вставить этот блок сюда, так как из самих ролей директива hosts не работает
#---------------------------------------------------------------------
- hosts: web_node
  become: true
  tasks:
    - name: Set a hostname to web_server
      ansible.builtin.hostname:
        name: "{{ variables.web_node_hostname }}"

- hosts: rproxy
  become: true
  tasks:
    - name: Set a hostname to rproxy
      ansible.builtin.hostname:
        name: "{{ variables.rproxy_hostname }}"

- hosts: db01
  become: true
  tasks:
    - name: Set a hostname to db01
      ansible.builtin.hostname:
        name: "{{ variables.db01_node_hostname }}"

- hosts: db02
  become: true
  tasks:
    - name: Set a hostname to db02
      ansible.builtin.hostname:
        name: "{{ variables.db02_node_hostname }}"

- hosts: gitlab_node
  become: true
  tasks:
    - name: Set a hostname to gitlab
      ansible.builtin.hostname:
        name: "{{ variables.gitlab_node_hostname }}"

- hosts: gitlabrunner_node
  become: true
  tasks:
    - name: Set a hostname to gitlabrunner
      ansible.builtin.hostname:
        name: "{{ variables.gitlabrunner_node_hostname }}"

- hosts: monitoring_node
  become: true
  tasks:
    - name: Set a hostname to monitoring
      ansible.builtin.hostname:
        name: "{{ variables.monitoring_node_hostname }}"
#---------------------------------------------------------------


# Развёртывание rproxy c nginx на нём 
- hosts: rproxy
  become: true
  roles:
    - rproxy

# Развёртывание Web-cервера c Apache и Wordpress
- hosts: web_node
  become: true
  roles:
    - webserver

# Установка Mysql Cluster Management на первый срвер БД
- hosts: db01
  become: true
  roles:
    - mysql-cluster-management

# Установка Mysql Cluster Data-Nodes на оба сервера БД
- hosts: db_nodes
  become: true
  roles:
    - mysql-cluster-datanode

# Установка Mysql Server and Client на первый сервер БД
# А также создаём БД для сайта на wordpress
- hosts: db01
  become: true
  roles:
    - mysql-cluster-sqlnode

# Развёртывание gitlab
- hosts: gitlab_node
  become: true
  roles:
    - gitlab

# Развёртывание gitlab runner
- hosts: gitlabrunner_node
  become: true
  roles:
    - gitlabrunner

# Развёртывание Grafana, Prometheus, Alert Manager
- hosts: monitoring_nodes
  become: true
  roles:
    - monitoring
