---
# Переименовываем хосты

- hosts: web_node
  become: true
  tasks:
    - name: Set a hostname1
      ansible.builtin.hostname:
        name: "{{ variables.web_node_hostname }}"


- hosts: rproxy
  become: true
  tasks:
    - name: Set a hostname7
      ansible.builtin.hostname:
        name: "{{ variables.rproxy_hostname }}"


- hosts: db01
  become: true
  tasks:
    - name: Set a hostname2
      ansible.builtin.hostname:
        name: "{{ variables.db01_node_hostname }}"

- hosts: db02
  become: true
  tasks:
    - name: Set a hostname3
      ansible.builtin.hostname:
        name: "{{ variables.db02_node_hostname }}"

- hosts: gitlab_node
  become: true
  tasks:
    - name: Set a hostname4
      ansible.builtin.hostname:
        name: "{{ variables.gitlab_node_hostname }}"

- hosts: gitlabrunner_node
  become: true
  tasks:
    - name: Set a hostname4
      ansible.builtin.hostname:
        name: "{{ variables.gitlabrunner_node_hostname }}"


- hosts: monitoring_node
  become: true
  tasks:
    - name: Set a hostname4
      ansible.builtin.hostname:
        name: "{{ variables.monitoring_node_hostname }}"
