---
- name: Podgotovka Sistemi na grafana_node
  hosts: grafana_node
  become: true

  vars:
    dst_hosts_file: /etc/hosts
    src_hosts_file: ../../commonfiles/hosts

  tasks:

# Переименовываем хост. Значение переменной будет передаваться из командной строки в ключе команды ansible-playbook при запуске из terraform
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ grafana_node_hostname }}"


# Устанавливаем Московскую временную зону
    - name: Set timezone to Europe/Moscow
      community.general.timezone:
        name: Europe/Moscow

# копируем файл hosts
    - name: Copy file hosts
      copy:
        src: "{{ src_hosts_file }}"
        dest: "{{ dst_hosts_file }}"
        force: yes


# Обновляем все пакеты в системе
    - name: Update repos
      apt:
        update_cache: yes

# Устанавливаем nginx
#    - name: install nginx
#      apt:
#        name: nginx
#        state: latest




#    - name: install pytho3
#      apt:
#        name: python3
#        state: latest

#    - name: install python3-pip
#      apt:
#        name: python3-pip
#        state: latest

#    - name: install ansible
#      shell: python3 -m pip install ansible-core==2.13.1

#    - name: Create directory for playbok for Nodes
#      file: state=directory mode=0775 dest=/root/playbook_for_nodes

#    - name: Copy Playbook for nodes
#      copy: src=provision_nodes.yaml dest=/root/playbook_for_nodes
#      ignore_errors: yes

#    - name: Copy Playbook for nodes for Repeat Test
#      copy: src=provision_nodes_repeat-test.yaml dest=/root/playbook_for_nodes
#      ignore_errors: yes

#    - name: Copy nodes Inventory
#      copy: src=inventory_nodes dest=/root/playbook_for_nodes
#      ignore_errors: yes
