
# Терраформ создаёт inventory файл для ansible для настройки monitoring_node
resource "local_file" "inventory_monitoring_node" {
  content = <<-DOC
# Ansible inventory containing variable values from Terraform.
# Generated by Terraform.
[nodes:children]
monitoring_nodes
[monitoring_nodes]

monitoring_node ansible_host=${aws_instance.diplom-vm-monitoring_node.private_ip} ansible_ssh_private_key_file=~/.ssh/${aws_key_pair.kp.key_name}.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q ubuntu@${aws_instance.diplom-vm-rproxy.public_ip} -i ~/.ssh/${aws_key_pair.kp.key_name}.pem -oStrictHostKeyChecking=accept-new"'

    DOC
  filename = "../ansible/monitoring_node/inventory_monitoring_node"

  depends_on = [
    aws_instance.diplom-vm-monitoring_node
  ]
}
