# Читаем переменные
- name: Reading config
  ansible.builtin.include_vars:
    file: variables.yaml
    name: variables

# Устанавливаем зависимости
- name: Install dependencies
  apt:
    package:
        - python3-mysqldb
        - libmecab2
    state: present
    force: yes

# Скачиваем и устанавливаем Все элементы Mysql, включая Сервер и Клиент
- name: Download mysql common pack
  get_url:
    url: https://dev.mysql.com/get/Downloads/MySQL-Cluster-8.0/mysql-common_8.0.30-1ubuntu20.04_amd64.deb
    dest: /home/ubuntu/

- name: install mysql common pack
  shell: dpkg -i mysql-common_8.0.30-1ubuntu20.04_amd64.deb

- name: Download mysql cluster community client plugin pack
  get_url:
    url: https://dev.mysql.com/get/Downloads/MySQL-Cluster-8.0/mysql-cluster-community-client-plugins_8.0.30-1ubuntu20.04_amd64.deb
    dest: /home/ubuntu/

- name: install cluster community clinet plugin pack
  shell: dpkg -i mysql-cluster-community-client-plugins_8.0.30-1ubuntu20.04_amd64.deb

- name: Download mysql cluster community client core pack
  get_url:
    url: https://dev.mysql.com/get/Downloads/MySQL-Cluster-8.0/mysql-cluster-community-client-core_8.0.30-1ubuntu20.04_amd64.deb
    dest: /home/ubuntu/

- name: install cluster community clinet core pack
  shell: dpkg -i mysql-cluster-community-client-core_8.0.30-1ubuntu20.04_amd64.deb

- name: Download mysql cluster community client pack
  get_url:
    url: https://dev.mysql.com/get/Downloads/MySQL-Cluster-8.0/mysql-cluster-community-client_8.0.30-1ubuntu20.04_amd64.deb
    dest: /home/ubuntu/

- name: install cluster community clinet pack
  shell: dpkg -i mysql-cluster-community-client_8.0.30-1ubuntu20.04_amd64.deb

- name: Download mysql client pack
  get_url:
    url: https://dev.mysql.com/get/Downloads/MySQL-Cluster-8.0/mysql-client_8.0.30-1ubuntu20.04_amd64.deb
    dest: /home/ubuntu/

- name: install mysql  clinet pack
  shell: dpkg -i mysql-client_8.0.30-1ubuntu20.04_amd64.deb

- name: Download mysql cluster community server core pack
  get_url:
    url: https://dev.mysql.com/get/Downloads/MySQL-Cluster-8.0/mysql-cluster-community-server-core_8.0.30-1ubuntu20.04_amd64.deb
    dest: /home/ubuntu/

- name: install cluster community server core pack
  shell: dpkg -i mysql-cluster-community-server-core_8.0.30-1ubuntu20.04_amd64.deb

- name: Download mysql cluster community server pack
  get_url:
    url: https://dev.mysql.com/get/Downloads/MySQL-Cluster-8.0/mysql-cluster-community-server_8.0.30-1ubuntu20.04_amd64.deb
    dest: /home/ubuntu/

# На этом месте возникла тяжёлая проблема, отнявшая очень много времени
# Инсталлятор mysql-cluster-community-server  переходит в интерактивный режим и не выполняеся в фоне. Он задаёт вопросы про пароль рута и др.
# Следующие 3 таски делают как-бы автоответы на вопросы и инсталлятор потом выполнится без вопросов.

- name: Make answer for root password for installing mysql-community-server
  debconf:
    name: mysql-cluster-community-server
    question: mysql-cluster-community-server/root-pass
    value: "{{ variables.db_nodes_mysql_root_password }}"
    vtype: password

- name: Make answer for retype root password for installing mysql-community-server
  debconf:
    name: mysql-cluster-community-server
    question: mysql-cluster-community-server/re-root-pass
    value: "{{ variables.db_nodes_mysql_root_password }}"
    vtype: password

- name: Make answer for Authentication Methodfor installing mysql-community-server
  debconf:
    name: mysql-cluster-community-server
    question: mysql-server/default-auth-override
    value: 'Use Legacy Authentication Method (Retain MySQL 5.x Compatibility)'
    vtype: select


- name: install cluster community server package
  shell: dpkg -i mysql-cluster-community-server_8.0.30-1ubuntu20.04_amd64.deb

- name: Create mysql group
  group: name=mysql system=yes

- name: Create myslq user
  user: name=mysql system=yes createhome=no group=mysql

# Копируем файл настроек Mysql сервера, заполняя его на ходу.
- name: Install config
  template: src=my.cnf dest=/etc/mysql/my.cnf

# Запускаем сервер и включаем авто-старт
- name: Activate init script and start mysql server
  service: name=mysql.service enabled=yes state=restarted

# Создаём БД для wordpress
- name: Create a new database called wordpress
  mysql_db:
    login_user: root
    login_password: "{{ variables.db_nodes_mysql_root_password }}"
    name: "{{ variables.db_wordpress_dbname }}"
    state: present

# Создаём юзера для работы сайта с базой и Настраиваем ему право удалённоо подключения к серверу БД
- name: Configure new MySQL user wordpress for Wordpress connect to BD form any host
  mysql_user:
    login_user: root
    login_password: "{{ variables.db_nodes_mysql_root_password }}"
    name: "{{ variables.db_wordpress_dbusername }}"
    password: "{{ variables.db_wordpress_dbuserpassword }}"
    host: '%'
    priv: '{{ variables.db_wordpress_dbname }}.*:ALL'
#    priv: 'wordpress.*:ALL'


# ----------- Проверка состояния кластера ------------------
- name: Test of Cluster
  shell: /usr/bin/ndb_mgm -e SHOW
  register: command_output

- name: Print Status of Cluster
  debug:
    msg: "{{ command_output.stdout_lines }}"

- name: Test of Cluster
  shell: mysql -u root -p{{ variables.db_nodes_mysql_root_password }} -e 'SHOW ENGINE NDB STATUS \G'
  register: command_output

- name: Print Status of NDB
  debug:
    msg: "{{ command_output.stdout_lines }}"

