---
- name: Podgotovka Sistemi na vseh db_nodes
  hosts: db_nodes
  become: true

  vars:
    dst_hosts_file: /etc/hosts
    src_hosts_file: ../commonfiles/hosts

  tasks:

# Устанавливаем Московскую временную зону
    - name: Set timezone to Europe/Moscow
      community.general.timezone:
        name: Europe/Moscow

# копируем файл hosts
    - name: Copy file hosts
      copy:
        src: "{{ src_hosts_file }}"
        dest: "{{ dst_hosts_file }}"
        force: yes

# Обновляем все пакеты в системе
    - name: Update repos
      apt:
        update_cache: yes


- name: Podgotovka Sistemi na db_node-1
  hosts: db01
  become: true

  tasks:

# Переименовываем хост. Значение переменной будет передаваться из командной строки в ключе команды ansible-playbook при запуске из terraform
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ db01_node_hostname }}"

- name: Podgotovka Sistemi na db_node-2
  hosts: db02
  become: true

  tasks:

# Переименовываем хост. Значение переменной будет передаваться из командной строки в ключе команды ansible-playbook при запуске из terraform
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ db02_node_hostname }}"
