- name: Reading config
  ansible.builtin.include_vars:
    file: variables.yaml
    name: variables

- name: Print Status of Cluster
  debug:
    msg: "{{ command_output.stdout_lines }}"

- name: Test of Cluster
  shell: mysql -u root -p{{ variables.db_nodes_mysql_root_password }} -e 'SHOW ENGINE NDB STATUS \G'
  register: command_output

- name: Print Status of NDB
  debug:
    msg: "{{ command_output.stdout_lines }}"

