---
#      EXTERNAL_URL: "http://{{ gitlab_node_hostname }}"
#      GITLAB_ROOT_PASSWORD: "{{ gitlab_root_password }}"
#      GITLAB_SHARED_RUNNERS_REGISTRATION_TOKEN: "{{ gitlab_runner_init_token }}"

- name: Install Docker Engine
  hosts: gitlabrunner_node
  become: true
  tasks:
    - name: remove other versions of docker
      ansible.builtin.apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runcansible
        state: absent
    - name: install repo key for docker for debian
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        keyring: /etc/apt/trusted.gpg.d/docker.gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

#    - name: add repo for docker
#      ansible.builtin.apt_repository:
#        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/debian {{ ansible_facts['distribution_release'] }} stable"
#        state: present

    - name: install docker for debian
      ansible.builtin.apt:
        update_cache: true
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin

- name: Install gitlab runner on gitlabrunner_node
  hosts: gitlabrunner_node
  become: true

  tasks:

    - name: Download gitlab runner package
      get_url:
        url:  https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb
        dest: /home/ubuntu/gitlab-runner_amd64.deb

    - name: Install gitlab runner
      command: dpkg -i gitlab-runner_amd64.deb

#    - name: Register gitlab runner to Gitlab server
#      command: | 
#        gitlab-runner register --non-interactive --url "http://{{ gitlab_node_hostname  }}" --registration-token "{{ gitlab_runner_init_token }}" 
#        --executor "docker"  --docker-image alpine:latest --description "docker-runner" --maintenance-note "this runner can makes all" 
#        --tag-list "docker,aws" --run-untagged="true" --locked="false" --access-level="not_protected" --docker-network-mode="host"

# регистрируем gitlab-runner на сервере gitab. Он будет на основе docker внутрь прокидываем папку где лежит ключ для того, чтобы раннер смог выгружать файлы на вебсервер. Важно, также указать режим сети докера, как host.
    - name: Register gitlab runner to Gitlab server
      command: | 
        gitlab-runner register --non-interactive --url "http://{{ gitlab_node_hostname  }}" --registration-token "{{ gitlab_runner_init_token }}" 
        --executor "docker"  --docker-image "ubuntu:latest" --description "docker-runner" --maintenance-note "this runner can makes all" 
        --tag-list "docker,aws" --run-untagged="true" --locked="false" --access-level="not_protected" --docker-network-mode="host" --docker-volumes "/home/ubuntu/.ssh:/ssh"

