---
- name: Nastriyka Nginx
  hosts: rproxy
  become: true

  vars:
    config_path: /etc/nginx/
    src_nginx_conf: ../files/nginx.conf

  tasks:
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Copy config for Nginx
      copy:
        src: "{{ src_nginx_conf }}"
        dest: "{{ config_path }}"
#        mode: preserve
        force: yes
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted