---
- name: Podgotovka Sistemi na web_node
  hosts: web_node
  become: true

  vars:
    dst_hosts_file: /etc/hosts
    src_hosts_file: ../commonfiles/hosts

  tasks:

# Переименовываем хост. Значение переменной будет передаваться из командной строки в ключе команды ansible-playbook при запуске из terraform
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ web_node_hostname }}"


# Устанавливаем Московскую временную зону
    - name: Set timezone to Europe/Moscow
      community.general.timezone:
        name: Europe/Moscow

# копируем файл hosts
    - name: Copy file hosts
      copy:
        src:  "{{ src_hosts_file }}"
        dest: "{{ dst_hosts_file }}"
        force: yes

# Обновляем все пакеты в системе
    - name: Update repos
      apt:
        update_cache: yes
