---
- name: Reading config
  ansible.builtin.include_vars:
    file: variables.yaml
    name: variables

# Даём хосту имя
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ variables.web_node_hostname }}"

- name: Install Apache and php neededs
  ansible.builtin.apt:
    pkg:
            - apache2
            - libapache2-mod-php
            - php-cli
            - php-gd
            - php-fpm
            - php-common
            - php-mbstring
            - php-xmlrpc
            - php-xml
            - php-mysql
            - php-zip
            - php-curl
    state: present
    force: yes

- name: Install Wordpress
  block:
    - name: Download and Extract WorPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: /var/www/
        remote_src: yes

    - name: Update default Apache site
      lineinfile:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: present
        regexp: '(.)+DocumentRoot /var/www/html'
        line: 'DocumentRoot /var/www/wordpress'

    - name: Rename sample config file to config
      command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php

    - name: Insert parameters to Wordpress config file
      lineinfile:
        path: /var/www/wordpress/wp-config.php
        regexp: "{{item.regexp}}"
        line: "{{item.line}}"
      with_items:
        - {'regexp': "define\\( 'DB_HOST', '(.)+' \\);", 'line': "define( 'DB_HOST', '{{ variables.db_wordpress_dbhost }}' );"}
        - {'regexp': "define\\( 'DB_NAME', '(.)+' \\);", 'line': "define( 'DB_NAME', '{{ variables.db_wordpress_dbname }}' );"}
        - {'regexp': "define\\( 'DB_USER', '(.)+' \\);", 'line': "define( 'DB_USER', '{{ variables.db_wordpress_dbusername }}' );"}
        - {'regexp': "define\\( 'DB_PASSWORD', '(.)+' \\);", 'line': "define( 'DB_PASSWORD', '{{ variables.db_wordpress_dbuserpassword }}' );"}

- name: Restart Apache
  service:
    name: apache2
    state: restarted


# даём права на папку с сайтом. группа ubuntu добавлена, чтобы раннер смог заливать файлы

- name: Update ownership to Apache user and Ubuntu
  file:
    path: /var/www/wordpress/
    state: directory
    recurse: yes
    owner: www-data
    group: ubuntu

- name: Set the correct permissions on Wordpress directories
  command: find /var/www/wordpress/ -type d -exec chmod 770 {} \;
